name: location_bloc
description: Location provided with the bloc pattern based on the location package
version: 0.0.1
author: Joerg Hilger
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: 1.2.2
  flutter:
    sdk: flutter
  location: 3.0.2
  logging: 0.11.4
  super_enum: 0.4.2
  bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.0
  bloc_test: 6.0.1
  mockito: 4.1.1
  test: 1.14.4
  test_api: 0.2.15

# The following section is specific to Flutter.
flutter:

